version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: 'gitlab.127.0.0.1.nip.io'  # Replace 127.0.0.1 with your server's public IP
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.127.0.0.1.nip.io'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_host'] = 'postgres'
        gitlab_rails['db_port'] = 5432
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = '$T6z#p@Q9d2!fG7'
        gitlab_rails['db_database'] = 'gitlabhq_production'
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = 6379
        gitlab_rails['redis_password'] = '$T6z#p@Q9d2!fG7'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: 'gitlab'
      POSTGRES_PASSWORD: 'gitlab_password'
      POSTGRES_DB: 'gitlabhq_production'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  postgres-data:
  redis-data: